contact_links:
  - name: Question ğŸ¤·ğŸ»â€â™‚ï¸
    url: https://github.com/Marc-Bernard-Tools/MBT-Package-Manager/discussions/new?category=q-a
    about: ğŸ†• Open a new Q&A discussion ğŸ™
  - name: Security Report ğŸ›¡
    url: https://marcbernardtools.com/about/security/
    about: I want to report a security vulnerability
  - name: Chat ğŸ˜
    url: https://communityinviter.com/apps/marc-bernard-tools/join-our-slack-community
    about: Quick question? Try out Slack chat, you can get faster feedback
